### ISSUE TITLE
When project gets bigger SoftI2CMaster wont complie because of rcalls and rjmps

### ISSUE THREAD

**Issue by zakzag** [felias-fogg/SoftI2CMaster#23]
When one's project grows, eventually  it gets to the point where SoftI2CMaster won't compile, as rcalls and rjmps are out of bounds, so they need to be replaced to call and jmp respectively.

**Comment by felias-fogg** [comment]
Never happened to me although although I write fairly large programs.

Could you send me an example? 

I believe that this should not happen since the relative calls and jumps are only inside the code, which should stick together regardless how large you project is. But would be interesting to see when it happens nevertheless.
