### ISSUE TITLE
Remove dependency on Arduino.h

### ISSUE THREAD

**Issue by ToxicFrog** [felias-fogg/SoftI2CMaster#41]
It looks like this is only needed for the `bool` type; I was able to get it working fine with just avr-gcc, no Arduino libraries, by removing the `#include` and replacing it with:

    typedef uint8_t bool;
    #define false ((bool)0)
    #define true ((bool)~false)

**Comment by felias-fogg** [comment]
For plain avr-gcc, you could use Peter Fleury's original assembler program.  Moreover, _bool_ is actually a C++ type. The recommended Arduino type is _boolean_, which is a bit confusing. So I am not sure why Arduino.h is needed for this. Probably, because it itself includes some standard C++ typedefs. In any case, I could probably could get rid of this include ... maybe sometimes in the future.
