### ISSUE TITLE
ESP8266

### ISSUE THREAD

**Issue by SMotlaq** [felias-fogg/SoftI2CMaster#59]
Hi, I'm using an ESP based Arduino board (Wemos D1 mini) and I need to use a vitrual I2C as slave. How can I do that?

**Comment by felias-fogg** [comment]
Sorry, I cannot help you in this respect. Programming a slave is much more difficult than programming a master. The reason is that there are tight timing constraints and that the program logic itself (using callbacks) is more complicated. I tried out a few software I2C clients for ATtinys and was not really satisfied.

Best,
Bernhard
